### ISSUE TITLE
interactor name/picture does not show up

### ISSUE THREAD

**Issue by luto** [socialhubio/socialhub-dev#10]
1. POST to `/inbox/tickets`:
```
{'interaction': {'message': '@dev blubb2',
                 'networkItemId': 'mastodon_uberspace-social_104166463983639697',
                 'url': 'https://chaos.social/@luto/104166463971081736',
                 'interactor': {'interactorId': 'mastodon-account-uberspace-social-51',
                                'name': 'luto',
                                'url': 'https://chaos.social/@luto',
                                'picture': 'https://uberspace.social/system/accounts/avatars/000/000/051/original/4c4a45b5b1f3b42a.png?1588771106'}}}
```
2. open socialhub
3. name and picture of the passed interactor do not show up
![image](https://user-images.githubusercontent.com/2158203/81927087-59819200-95e3-11ea-8156-b92a66f8b78c.png)

Can you give me a hint as to what I am doing wrong, please? :)

**Comment by patrickd-** [comment]
Interactor fields are part of API v1.1 which will be rolled out this weekend, see [changelog](https://socialhub.dev/docs/en/changelog#version-11) :+1:

**Comment by patrickd-** [comment]
PS.: please consider subscribing to our API changelog newsletter http://eepurl.com/g2EiC1

**Comment by luto** [comment]
ah! Thanks for the heads-up :) subscribed.

**Comment by luto** [comment]
@patrickd- were the changes deployed successfully?

**Comment by patrickd-** [comment]
@luto It seems like we've been having trouble with deploying the latest release due to some more fundamental changes that were introduced. I'll write a newsletter as soon as it's deployed. Sorry for the inconvenience

**Comment by luto** [comment]
okay, thanks! :)

**Comment by luto** [comment]
Congrats on the deployment! The usernames and links for interactors now show up :tada: The avatars don't, though. Can you please take a look and give us a hint? :) e.g. ticket `5ec51e93816eaa4e4297ca0e`.

**Comment by patrickd-** [comment]
Hey thanks, sorry for the late reply! I had a look at your ticket and the picture was definitely set correctly. Problem is that it's being overwritten by the Custom Channel Image by default. This is another one of those things that we need to change for the WhatsApp Integration but we didn't get to do it yet due to other things suddenly being more important... I'll mention this tomorrow in the daily and ask our frontend team to implement it if it's not too much work, but it'll be a couple weeks until it'll hit release :grimacing:

**Comment by patrickd-** [comment]
We discussed it and since it's a simple change we'll fix it soon. So this should work within a couple weeks. Hope that helps

**Comment by luto** [comment]
nice to hear. Thank you! :) :tada:

**Comment by luto** [comment]
@patrickd- The avatars are looking great now. Thank you very much! :)
