### ISSUE TITLE
like button for custom channels

### ISSUE THREAD

**Issue by luto** [socialhubio/socialhub-dev#11]
Is there a way to add a "like" button within socialhub in a custom channel? The official twitter channel does have one and I was wondering if I can add one myself too.

Thanks!

**Comment by patrickd-** [comment]
Unfortunately not yet.

This is planned to work with the Ticket Actions which can be defined within Manifests. At this moment we only support `template_reply` and `reply` – we'd like to add other Actions like `button` (eg. for "delete") and `toggleButton` (eg. for "Like" and "Unlike") in the future.

At least a simple `button`-action should be easy to add, I'll mention this in the next team meeting.

**Comment by patrickd-** [comment]
BTW, if you don't mind doing a kind of dirty workaround: You can register a `reply` action called "Like" and simply ignore the textbox and the text value when you get the reply event data.

Or call it "Like and Reply" and only create a reply if there's text but always like..

**Comment by luto** [comment]
ha, I see ;) thanks!

**Comment by patrickd-** [comment]
We created a low priority task for implementing a `button` action in the API. We'll send a newsletter out when it's been deployed but it'll probably take a couple weeks.
