### ISSUE TITLE
swagger.yaml is invalid: bad indentation of a mapping entry

### ISSUE THREAD

**Issue by luto** [socialhubio/socialhub-dev#7]
According to [the petstore](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/socialhubio/socialhub-dev/master/swagger.yaml#/) the current swagger.yaml is not valid. dc0b120f24cef729303561d75adae2cf765f95da seems to be the faulty commit.

> Parser error on line 140
> bad indentation of a mapping entry

**Comment by patrickd-** [comment]
We just started re-working the documentation yesterday and for that I quickly merged all of the pull requests, looks like this error went in without noticing. I'll take a look at your pull requests later, thank you!
